// dx-engine 권고 문자열 현지화 — 엔진(무수정 이식, 영어 생성)을 건드리지 않고 표시층에서
// 번역한다. i18n-terms의 TERMS/RULES는 한국어 소스 방향이라 못 쓰므로, 이 모듈이 영어
// 소스 패턴(엔진 룰 템플릿 전수, 보간부는 캡처 그룹) → ko/zh/ja 방향을 담당한다.
// 미매칭 문자열은 원문 그대로 통과(zero-risk fallback) — 엔진 업스트림이 문구를 바꾸면
// 영어로 표시될 뿐 깨지지 않고, dx-engine.test의 커버리지 테스트가 누락을 잡는다.
// 기술 고유명사(BGP/VIF/LAG/BFD/DPD/SLA 티어명)는 원어 유지.
import type { Lang } from '../i18n';

type Gen = (m: RegExpMatchArray) => string;
interface Entry { re: RegExp; ko: Gen; zh: Gen; ja: Gen }

// slaLabel 보간부 공용 변환 ('Maximum Resiliency (99.99% SLA)' | 'High Resiliency (99.9% SLA)')
const sla = {
  ko: (s: string) => (s.startsWith('Maximum') ? 'Maximum Resiliency(99.99% SLA)' : 'High Resiliency(99.9% SLA)'),
  zh: (s: string) => (s.startsWith('Maximum') ? 'Maximum Resiliency（99.99% SLA）' : 'High Resiliency（99.9% SLA）'),
  ja: (s: string) => (s.startsWith('Maximum') ? 'Maximum Resiliency（99.99% SLA）' : 'High Resiliency（99.9% SLA）'),
};

const T: Entry[] = [
  // ── 티어 갭 권고 제목 (resiliency + public VIF 변형) ──
  { re: /^Add a Second Direct Connect Location for Public VIF$/,
    ko: () => 'Public VIF용 두 번째 Direct Connect 로케이션 추가',
    zh: () => '为 Public VIF 添加第二个 Direct Connect 位置',
    ja: () => 'Public VIF 用に 2 つ目の Direct Connect ロケーションを追加' },
  { re: /^Add a Second Direct Connect Location$/,
    ko: () => '두 번째 Direct Connect 로케이션 추가',
    zh: () => '添加第二个 Direct Connect 位置',
    ja: () => '2 つ目の Direct Connect ロケーションを追加' },
  { re: /^Add Redundant Connection at (.+) for Public VIF$/,
    ko: (m) => `${m[1]}에 Public VIF용 중복 연결 추가`,
    zh: (m) => `在 ${m[1]} 为 Public VIF 添加冗余连接`,
    ja: (m) => `${m[1]} に Public VIF 用の冗長接続を追加` },
  { re: /^Add Redundant Public VIF Path at (.+)$/,
    ko: (m) => `${m[1]}에 중복 Public VIF 경로 추가`,
    zh: (m) => `在 ${m[1]} 添加冗余 Public VIF 路径`,
    ja: (m) => `${m[1]} に冗長 Public VIF 経路を追加` },
  { re: /^Add Redundant Connection at (.+)$/,
    ko: (m) => `${m[1]}에 중복 연결 추가`,
    zh: (m) => `在 ${m[1]} 添加冗余连接`,
    ja: (m) => `${m[1]} に冗長接続を追加` },
  { re: /^Add Redundant LAG at (.+)$/,
    ko: (m) => `${m[1]}에 중복 LAG 추가`,
    zh: (m) => `在 ${m[1]} 添加冗余 LAG`,
    ja: (m) => `${m[1]} に冗長 LAG を追加` },
  { re: /^Add LAG at a Second Direct Connect Location$/,
    ko: () => '두 번째 Direct Connect 로케이션에 LAG 추가',
    zh: () => '在第二个 Direct Connect 位置添加 LAG',
    ja: () => '2 つ目の Direct Connect ロケーションに LAG を追加' },
  { re: /^Consider Using Transit Gateway$/,
    ko: () => 'Transit Gateway 사용 검토',
    zh: () => '考虑使用 Transit Gateway',
    ja: () => 'Transit Gateway の利用を検討' },
  { re: /^Add Redundant Virtual Private Gateway$/,
    ko: () => '중복 Virtual Private Gateway 추가',
    zh: () => '添加冗余 Virtual Private Gateway',
    ja: () => '冗長 Virtual Private Gateway を追加' },
  { re: /^Consider Using LAG Groups$/,
    ko: () => 'LAG 그룹 사용 검토',
    zh: () => '考虑使用 LAG 组',
    ja: () => 'LAG グループの利用を検討' },

  // ── 티어 갭 권고 설명 (조합형: topology/public VIF × reuse/추가 × High/Max) ──
  { re: /^Your (topology|public VIF connectivity) uses only one Direct Connect location\. (?:Reuse your existing Direct Connect location (\S+)(?: for this gateway)?|Adding a second location)( with two redundant connections)? provides (Maximum[^)]+\)|High[^)]+\)) by eliminating (both site and device failure|single-site failure)\.$/,
    ko: (m) => `${m[1] === 'topology' ? '현재 토폴로지는' : '현재 Public VIF 연결은'} Direct Connect 로케이션을 하나만 사용합니다. ${m[2] ? `기존 로케이션 ${m[2]}을(를) 이 경로에 재사용하고` : '두 번째 로케이션을 추가하고'}${m[3] ? ' 중복 연결 2개를 두면' : ''}${m[3] ? '' : ' 확장하면'} ${sla.ko(m[4])}에 도달해 ${m[5] === 'single-site failure' ? '단일 사이트 장애' : '사이트·디바이스 장애 모두'}를 제거합니다.`,
    zh: (m) => `${m[1] === 'topology' ? '当前拓扑' : '当前 Public VIF 连接'}仅使用一个 Direct Connect 位置。${m[2] ? `将现有位置 ${m[2]} 复用于此路径` : '添加第二个位置'}${m[3] ? '并配置两条冗余连接' : ''}即可达到 ${sla.zh(m[4])}，消除${m[5] === 'single-site failure' ? '单站点故障' : '站点与设备双重故障'}。`,
    ja: (m) => `${m[1] === 'topology' ? '現在のトポロジは' : '現在の Public VIF 接続は'} Direct Connect ロケーションを 1 つしか使用していません。${m[2] ? `既存ロケーション ${m[2]} をこの経路に再利用し` : '2 つ目のロケーションを追加し'}${m[3] ? '冗長接続を 2 本置くことで' : 'てください。これにより'} ${sla.ja(m[4])} に到達し、${m[5] === 'single-site failure' ? '単一サイト障害' : 'サイト・デバイス両方の障害'}を排除できます。` },
  { re: /^Location (.+) has only one Direct Connect connection( for public VIF)?\. Adding a second connection on a separate device provides Maximum[^)]+\)\.$/,
    ko: (m) => `로케이션 ${m[1]}에 ${m[2] ? 'Public VIF용 ' : ''}Direct Connect 연결이 하나뿐입니다. 별도 디바이스에 두 번째 연결을 추가하면 Maximum Resiliency(99.99% SLA)에 도달합니다.`,
    zh: (m) => `位置 ${m[1]} ${m[2] ? '仅有一条用于 Public VIF 的' : '仅有一条'} Direct Connect 连接。在独立设备上添加第二条连接即可达到 Maximum Resiliency（99.99% SLA）。`,
    ja: (m) => `ロケーション ${m[1]} には${m[2] ? ' Public VIF 用の' : ''} Direct Connect 接続が 1 本しかありません。別デバイスに 2 本目の接続を追加すると Maximum Resiliency（99.99% SLA）に到達します。` },
  { re: /^Location (.+) has (\d+) connections( for public VIF)?, but they terminate on the same AWS logical device[^.]*\. Add a connection on a separate device to reach Maximum[^)]+\)\.$/,
    ko: (m) => `로케이션 ${m[1]}에 ${m[3] ? 'Public VIF용 ' : ''}연결이 ${m[2]}개 있지만 전부 같은 AWS 논리 디바이스에 종단됩니다 — 디바이스 장애 시 이 로케이션 전체가 끊깁니다. 별도 디바이스에 연결을 추가하면 Maximum Resiliency(99.99% SLA)에 도달합니다.`,
    zh: (m) => `位置 ${m[1]} 有 ${m[2]} 条${m[3] ? '用于 Public VIF 的' : ''}连接，但都终结在同一 AWS 逻辑设备上 — 设备故障将使该位置完全中断。在独立设备上添加连接即可达到 Maximum Resiliency（99.99% SLA）。`,
    ja: (m) => `ロケーション ${m[1]} には${m[3] ? ' Public VIF 用の' : ''}接続が ${m[2]} 本ありますが、すべて同一の AWS 論理デバイスに終端しています — デバイス障害でこのロケーション全体が切断されます。別デバイスに接続を追加すると Maximum Resiliency（99.99% SLA）に到達します。` },
  { re: /^Location (.+) has only one AWS logical device reaching this gateway\. (Adding a second (?:LAG|connection) on a separate AWS device) provides Maximum[^)]+\)\.$/,
    ko: (m) => `로케이션 ${m[1]}에서 이 게이트웨이에 도달하는 AWS 논리 디바이스가 하나뿐입니다. 별도 AWS 디바이스에 ${/LAG/.test(m[2]) ? '두 번째 LAG' : '두 번째 연결'}를 추가하면 Maximum Resiliency(99.99% SLA)에 도달합니다.`,
    zh: (m) => `位置 ${m[1]} 只有一台可达此网关的 AWS 逻辑设备。在独立 AWS 设备上添加${/LAG/.test(m[2]) ? '第二个 LAG' : '第二条连接'}即可达到 Maximum Resiliency（99.99% SLA）。`,
    ja: (m) => `ロケーション ${m[1]} でこのゲートウェイに到達する AWS 論理デバイスが 1 台しかありません。別の AWS デバイスに${/LAG/.test(m[2]) ? '2 つ目の LAG' : '2 本目の接続'}を追加すると Maximum Resiliency（99.99% SLA）に到達します。` },
  { re: /^Your LAG topology uses only one Direct Connect location \((.+)\)\. Adding a LAG at a second location provides (Maximum[^)]+\)|High[^)]+\)) by eliminating single-site failure\.$/,
    ko: (m) => `현재 LAG 토폴로지는 Direct Connect 로케이션을 하나(${m[1]})만 사용합니다. 두 번째 로케이션에 LAG를 추가하면 ${sla.ko(m[2])}에 도달해 단일 사이트 장애를 제거합니다.`,
    zh: (m) => `当前 LAG 拓扑仅使用一个 Direct Connect 位置（${m[1]}）。在第二个位置添加 LAG 即可达到 ${sla.zh(m[2])}，消除单站点故障。`,
    ja: (m) => `現在の LAG トポロジは Direct Connect ロケーションを 1 つ（${m[1]}）しか使用していません。2 つ目のロケーションに LAG を追加すると ${sla.ja(m[2])} に到達し、単一サイト障害を排除できます。` },
  { re: /^Using a Transit Gateway instead of multiple Virtual Private Gateways simplifies routing and enables better scalability\.$/,
    ko: () => '여러 Virtual Private Gateway 대신 Transit Gateway를 사용하면 라우팅이 단순해지고 확장성이 좋아집니다.',
    zh: () => '使用 Transit Gateway 替代多个 Virtual Private Gateway 可简化路由并提升可扩展性。',
    ja: () => '複数の Virtual Private Gateway の代わりに Transit Gateway を使用すると、ルーティングが簡素化され拡張性が向上します。' },
  { re: /^You have a single Virtual Private Gateway\. Consider adding a second one for redundancy\.$/,
    ko: () => 'Virtual Private Gateway가 하나뿐입니다. 이중화를 위해 두 번째 VGW 추가를 검토하세요.',
    zh: () => '当前只有一个 Virtual Private Gateway。建议添加第二个以实现冗余。',
    ja: () => 'Virtual Private Gateway が 1 つしかありません。冗長化のため 2 つ目の追加を検討してください。' },
  { re: /^Link Aggregation Groups can bundle multiple connections for simplified management\.$/,
    ko: () => 'LAG(Link Aggregation Group)로 여러 연결을 묶으면 관리가 단순해집니다.',
    zh: () => 'LAG（链路聚合组）可将多条连接捆绑，简化管理。',
    ja: () => 'LAG（リンク集約グループ）で複数接続を束ねると管理が簡素化されます。' },

  // ── 베스트 프랙티스 제목 ──
  { re: /^Virtual Interface\(s\) in DOWN State$/,
    ko: () => 'DOWN 상태의 Virtual Interface 존재',
    zh: () => '存在 DOWN 状态的 Virtual Interface',
    ja: () => 'DOWN 状態の Virtual Interface あり' },
  { re: /^Direct Connect Connection\(s\) Not Available$/,
    ko: () => 'available 상태가 아닌 Direct Connect 연결 존재',
    zh: () => '存在非 available 状态的 Direct Connect 连接',
    ja: () => 'available 状態でない Direct Connect 接続あり' },
  { re: /^No Site-to-Site VPN Backup$/,
    ko: () => 'Site-to-Site VPN 백업 없음',
    zh: () => '缺少 Site-to-Site VPN 备份',
    ja: () => 'Site-to-Site VPN バックアップなし' },
  { re: /^Ensure Bidirectional Forwarding Detection \(BFD\) is Enabled$/,
    ko: () => 'BFD(Bidirectional Forwarding Detection) 활성화 확인',
    zh: () => '确认已启用 BFD（双向转发检测）',
    ja: () => 'BFD（双方向フォワーディング検出）の有効化を確認' },
  { re: /^Verify Enterprise Support plan is in place$/,
    ko: () => 'Enterprise Support 플랜 보유 확인',
    zh: () => '确认已具备 Enterprise Support 计划',
    ja: () => 'Enterprise Support プランの保有を確認' },
  { re: /^Verify Well-Architected Review has been completed$/,
    ko: () => 'Well-Architected Review 완료 확인',
    zh: () => '确认已完成 Well-Architected Review',
    ja: () => 'Well-Architected Review の完了を確認' },
  { re: /^Understand Direct Connect SLA tiers$/,
    ko: () => 'Direct Connect SLA 티어 이해',
    zh: () => '了解 Direct Connect SLA 层级',
    ja: () => 'Direct Connect SLA ティアの理解' },
  { re: /^Use the Direct Connect Resiliency Toolkit for production workloads$/,
    ko: () => '프로덕션 워크로드에는 DX Resiliency Toolkit 사용',
    zh: () => '生产工作负载请使用 DX Resiliency Toolkit',
    ja: () => '本番ワークロードには DX Resiliency Toolkit を使用' },
  { re: /^Advertise the same prefixes across redundant VIFs$/,
    ko: () => '중복 VIF 간 동일 프리픽스 광고',
    zh: () => '在冗余 VIF 间通告相同前缀',
    ja: () => '冗長 VIF 間で同一プレフィックスを広告' },
  { re: /^Summarize prefixes and keep VIF routing symmetric$/,
    ko: () => '프리픽스 요약 및 VIF 라우팅 대칭 유지',
    zh: () => '汇总前缀并保持 VIF 路由对称',
    ja: () => 'プレフィックスを集約し VIF ルーティングを対称に維持' },
  { re: /^Configure LAG min-links — a LAG is not a resiliency mechanism$/,
    ko: () => 'LAG min-links 설정 — LAG는 복원력 장치가 아님',
    zh: () => '配置 LAG min-links — LAG 不是弹性机制',
    ja: () => 'LAG min-links を設定 — LAG はレジリエンス機構ではない' },
  { re: /^BGP route limit reached — session at risk of teardown$/,
    ko: () => 'BGP 라우트 한도 도달 — 세션 종료 위험',
    zh: () => '已达 BGP 路由上限 — 会话有中断风险',
    ja: () => 'BGP ルート上限に到達 — セッション切断リスク' },
  { re: /^BGP routes approaching the 100-prefix limit$/,
    ko: () => 'BGP 라우트가 100 프리픽스 한도에 근접',
    zh: () => 'BGP 路由接近 100 前缀上限',
    ja: () => 'BGP ルートが 100 プレフィックス上限に接近' },
  { re: /^BGP routes within the 100-prefix limit$/,
    ko: () => 'BGP 라우트가 100 프리픽스 한도 이내',
    zh: () => 'BGP 路由在 100 前缀上限之内',
    ja: () => 'BGP ルートは 100 プレフィックス上限内' },
  { re: /^Keep BGP routes under 100 per session$/,
    ko: () => '세션당 BGP 라우트를 100개 미만으로 유지',
    zh: () => '每个会话的 BGP 路由保持在 100 条以内',
    ja: () => 'セッションあたりの BGP ルートを 100 未満に維持' },
  { re: /^Ensure both VPN tunnels are UP for redundancy$/,
    ko: () => 'VPN 터널 2개 모두 UP 상태 유지',
    zh: () => '确保两条 VPN 隧道均为 UP 以实现冗余',
    ja: () => '冗長性のため VPN トンネル 2 本とも UP を維持' },
  { re: /^Deploy multiple customer gateways for device redundancy$/,
    ko: () => '디바이스 이중화를 위한 다중 Customer Gateway 배치',
    zh: () => '部署多个 Customer Gateway 以实现设备冗余',
    ja: () => 'デバイス冗長化のため複数の Customer Gateway を配置' },
  { re: /^Consider sourcing Direct Connect from multiple partners$/,
    ko: () => '복수 파트너로부터의 Direct Connect 조달 검토',
    zh: () => '考虑从多家合作伙伴采购 Direct Connect',
    ja: () => '複数パートナーからの Direct Connect 調達を検討' },
  { re: /^Enable DPD timeout action on VPN tunnels$/,
    ko: () => 'VPN 터널에 DPD timeout action 활성화',
    zh: () => '为 VPN 隧道启用 DPD 超时操作',
    ja: () => 'VPN トンネルで DPD タイムアウトアクションを有効化' },
  { re: /^Verify VPN Dead Peer Detection \(DPD\) on the customer gateway$/,
    ko: () => 'Customer Gateway 측 DPD 설정 확인',
    zh: () => '确认 Customer Gateway 侧的 DPD 配置',
    ja: () => 'Customer Gateway 側の DPD 設定を確認' },
  { re: /^Choose DX location redundancy that matches your risk profile$/,
    ko: () => '리스크 프로파일에 맞는 DX 로케이션 이중화 선택',
    zh: () => '选择符合风险特征的 DX 位置冗余方案',
    ja: () => 'リスクプロファイルに合った DX ロケーション冗長化を選択' },
  { re: /^Optimize BGP timers when BFD is not supported$/,
    ko: () => 'BFD 미지원 시 BGP 타이머 최적화',
    zh: () => '不支持 BFD 时优化 BGP 计时器',
    ja: () => 'BFD 非対応時は BGP タイマーを最適化' },
  { re: /^Conduct regular Direct Connect failover tests$/,
    ko: () => '정기적인 Direct Connect 페일오버 테스트 수행',
    zh: () => '定期进行 Direct Connect 故障切换测试',
    ja: () => 'Direct Connect フェイルオーバーテストを定期実施' },
  { re: /^Maintain documented DX\/VPN failover runbooks$/,
    ko: () => 'DX/VPN 페일오버 런북 문서화·유지',
    zh: () => '维护成文的 DX/VPN 故障切换手册',
    ja: () => 'DX/VPN フェイルオーバー Runbook を文書化・維持' },

  // ── 베스트 프랙티스 설명 (파라미터 캡처) ──
  { re: /^BGP is down on (.+) — no traffic can flow over (?:this path|these paths)\. Check the BGP configuration, VLAN tagging, and physical connectivity\.$/,
    ko: (m) => `${m[1]}에서 BGP가 다운돼 이 경로로 트래픽이 흐를 수 없습니다. BGP 설정, VLAN 태깅, 물리 연결을 점검하세요.`,
    zh: (m) => `${m[1]} 上的 BGP 已中断，此路径无法传输流量。请检查 BGP 配置、VLAN 标记与物理连接。`,
    ja: (m) => `${m[1]} で BGP がダウンしており、この経路をトラフィックが流れません。BGP 設定、VLAN タギング、物理接続を確認してください。` },
  { re: /^(\d+) connection\(s\) are not in "available" state: (.+)\. These connections are not passing traffic\. Check the AWS Console for provisioning status or errors\.$/,
    ko: (m) => `${m[1]}개 연결이 "available" 상태가 아닙니다: ${m[2]}. 이 연결들은 트래픽을 전달하지 못합니다. AWS 콘솔에서 프로비저닝 상태나 오류를 확인하세요.`,
    zh: (m) => `${m[1]} 条连接不处于 "available" 状态：${m[2]}。这些连接无法传输流量。请在 AWS 控制台检查预配状态或错误。`,
    ja: (m) => `${m[1]} 本の接続が "available" 状態ではありません: ${m[2]}。これらの接続はトラフィックを転送できません。AWS コンソールでプロビジョニング状況やエラーを確認してください。` },
  { re: /^No Site-to-Site VPN connections detected alongside Direct Connect\. AWS recommends configuring a VPN connection as a backup path[\s\S]*$/,
    ko: () => 'Direct Connect와 함께 구성된 Site-to-Site VPN이 없습니다. AWS는 DX 전체 장애(광케이블 절단, 로케이션 장애 등) 시 인터넷 기반 VPN 터널로 페일오버할 수 있도록 백업 VPN 구성을 권장합니다. 참고: VPN 백업은 DX SLA를 올려주지 않으며, 저하된 대역폭을 감내할 수 있는 예산 제약 환경에 유용한 페일오버 경로일 뿐입니다.',
    zh: () => '未检测到与 Direct Connect 并行的 Site-to-Site VPN。AWS 建议配置 VPN 作为备份路径，以便 DX 完全不可用（如光纤中断、位置故障）时流量可切换到基于互联网的 VPN 隧道。注意：VPN 备份不会提升 DX SLA，仅提供故障切换路径，适合可接受降级带宽的预算受限部署。',
    ja: () => 'Direct Connect と併設された Site-to-Site VPN が検出されませんでした。AWS は DX が完全に利用不能（ファイバー切断やロケーション障害など）になった際にインターネット経由の VPN トンネルへフェイルオーバーできるよう、バックアップ VPN の構成を推奨します。注: VPN バックアップは DX SLA を向上させず、帯域低下を許容できる予算制約下でのフェイルオーバー経路に有用です。' },
  { re: /^Without BFD, failover relies on BGP hold timers[\s\S]*$/,
    ko: () => 'BFD 없이는 페일오버가 BGP hold 타이머에 의존해 링크 장애 감지에 최대 90초가 걸립니다. BFD는 감지를 1초 미만으로 줄입니다. 최소 간격 300ms · liveness multiplier 3으로 BFD를 구성하고, BFD 기반 페일오버가 지연되지 않도록 BGP graceful restart는 비활성화하세요. BFD 상태는 AWS API로 조회되지 않으니 고객 라우터 설정에서 직접 확인해야 합니다. 참고: https://repost.aws/knowledge-center/enable-bfd-direct-connect',
    zh: () => '没有 BFD 时，故障切换依赖 BGP 保持计时器，检测链路故障最长需 90 秒。BFD 可将检测缩短到 1 秒以内。请以最小间隔 300ms、liveness 乘数 3 配置 BFD，并禁用 BGP graceful restart 以免延迟 BFD 驱动的切换。BFD 状态无法通过 AWS API 获取 — 请在客户路由器配置中确认。参见 https://repost.aws/knowledge-center/enable-bfd-direct-connect',
    ja: () => 'BFD がない場合、フェイルオーバーは BGP ホールドタイマーに依存し、リンク障害の検出に最大 90 秒かかります。BFD は検出を 1 秒未満に短縮します。最小間隔 300ms・liveness 乗数 3 で BFD を構成し、BFD 主導のフェイルオーバーが遅延しないよう BGP graceful restart は無効化してください。BFD の状態は AWS API では取得できないため、カスタマールーターの設定で確認が必要です。参考: https://repost.aws/knowledge-center/enable-bfd-direct-connect' },
  { re: /^Required for the 99\.9% and 99\.99% Direct Connect SLAs\. See (.+)$/,
    ko: (m) => `99.9% 및 99.99% Direct Connect SLA의 요건입니다. 참고: ${m[1]}`,
    zh: (m) => `这是 99.9% 与 99.99% Direct Connect SLA 的必要条件。参见 ${m[1]}`,
    ja: (m) => `99.9% および 99.99% の Direct Connect SLA の要件です。参考: ${m[1]}` },
  { re: /^Required for the 99\.99% Direct Connect SLA, in addition to Enterprise Support\. See (.+)$/,
    ko: (m) => `Enterprise Support에 더해 99.99% Direct Connect SLA의 요건입니다. 참고: ${m[1]}`,
    zh: (m) => `除 Enterprise Support 外，这也是 99.99% Direct Connect SLA 的必要条件。参见 ${m[1]}`,
    ja: (m) => `Enterprise Support に加えて 99.99% Direct Connect SLA の要件です。参考: ${m[1]}` },
  { re: /^AWS publishes three Direct Connect SLA tiers[\s\S]*$/,
    ko: () => 'AWS는 세 가지 Direct Connect SLA 티어를 제공합니다: Single Connection(95%), Multi-Site Non-Redundant / High Resiliency(99.9%, 2개 이상 로케이션), Multi-Site Redundant / Maximum Resiliency(99.99%, 로케이션 2개 이상 각각 디바이스 2개 이상). 최고 SLA는 Maximum Resiliency 모델만 해당합니다. 참고: https://aws.amazon.com/directconnect/sla/',
    zh: () => 'AWS 提供三个 Direct Connect SLA 层级：Single Connection（95%）、Multi-Site Non-Redundant / High Resiliency（99.9%，2 个以上位置）、Multi-Site Redundant / Maximum Resiliency（99.99%，2 个以上位置且每个位置 2 台以上设备）。只有 Maximum Resiliency 模型可获得最高 SLA。参见 https://aws.amazon.com/directconnect/sla/',
    ja: () => 'AWS は 3 つの Direct Connect SLA ティアを公開しています: Single Connection（95%）、Multi-Site Non-Redundant / High Resiliency（99.9%、2 拠点以上）、Multi-Site Redundant / Maximum Resiliency（99.99%、2 拠点以上・各拠点 2 デバイス以上）。最高 SLA の対象は Maximum Resiliency モデルのみです。参考: https://aws.amazon.com/directconnect/sla/' },
  { re: /^For production or mission-critical workloads, implement the High Resiliency or Maximum Resiliency model[\s\S]*$/,
    ko: () => '프로덕션·미션 크리티컬 워크로드에는 DX Resiliency Toolkit으로 High 또는 Maximum Resiliency 모델을 구현해 유지보수 이벤트 중에도 트래픽이 계속 흐르게 하세요. Development/Test 모델은 비프로덕션 워크로드에 비용 효율적입니다. 참고: https://docs.aws.amazon.com/directconnect/latest/UserGuide/resiliency_toolkit.html',
    zh: () => '对于生产或关键任务工作负载，请使用 DX Resiliency Toolkit 实现 High 或 Maximum Resiliency 模型，确保维护事件期间流量不中断。Development/Test 模型更适合非生产工作负载。参见 https://docs.aws.amazon.com/directconnect/latest/UserGuide/resiliency_toolkit.html',
    ja: () => '本番・ミッションクリティカルなワークロードでは、DX Resiliency Toolkit で High または Maximum Resiliency モデルを実装し、メンテナンスイベント中もトラフィックが流れ続けるようにしてください。Development/Test モデルは非本番向けに費用効率的です。参考: https://docs.aws.amazon.com/directconnect/latest/UserGuide/resiliency_toolkit.html' },
  { re: /^Validate that the same BGP prefixes are learned and advertised across redundant Virtual Interfaces[\s\S]*$/,
    ko: () => '중복 VIF들에서 동일한 BGP 프리픽스가 학습·광고되는지 검증하세요. 비대칭 광고는 페일오버 경로의 도달성을 다르게 만들어 페일오버 중 트래픽 블랙홀을 유발할 수 있습니다. BGP 라우트 상태는 AWS API로 조회되지 않으니 고객 라우터에서 확인하세요.',
    zh: () => '请验证冗余 VIF 间学习与通告的 BGP 前缀一致。不对称通告会使故障切换路径的可达性不同，切换期间可能造成流量黑洞。BGP 路由状态无法通过 AWS API 获取 — 请在客户路由器上确认。',
    ja: () => '冗長 VIF 間で同一の BGP プレフィックスが学習・広告されているか検証してください。非対称な広告はフェイルオーバー経路の到達性を変え、切替中のトラフィックブラックホールを招きます。BGP ルート状態は AWS API では取得できないため、カスタマールーターで確認してください。' },
  { re: /^Route summarization — advertising individual \/24s will exhaust the 100-prefix limit rapidly[\s\S]*$/,
    ko: () => '라우트 요약 — 개별 /24를 그대로 광고하면 100 프리픽스 한도가 빠르게 소진됩니다. 집계 프리픽스로 통합하세요. 같은 라우팅 도메인을 서빙하며 같은 DXGW/VGW에 연결된 모든 VIF는, 트래픽 조작이 필요한 경우가 아니라면 동일한 프리픽스 셋과 일관된 BGP 속성(local preference, AS_PATH 길이 등)을 광고·수신해야 합니다. BGP 라우트 상태는 AWS API로 조회되지 않으니 고객 라우터에서 확인하세요.',
    zh: () => '路由汇总 — 逐条通告 /24 会迅速耗尽 100 前缀上限，请合并为聚合前缀。服务同一路由域、连接同一 DXGW/VGW 的所有 VIF，除非需要流量工程，应通告并接收相同的前缀集与一致的 BGP 属性（local preference、AS_PATH 长度等）。BGP 路由状态无法通过 AWS API 获取 — 请在客户路由器上确认。',
    ja: () => 'ルート集約 — 個別の /24 をそのまま広告すると 100 プレフィックス上限がすぐ枯渇します。集約プレフィックスに統合してください。同一ルーティングドメインを担い同じ DXGW/VGW に接続する全 VIF は、トラフィック制御が必要な場合を除き、同一のプレフィックスセットと一貫した BGP 属性（local preference、AS_PATH 長など）を広告・受信すべきです。BGP ルート状態は AWS API では取得できないため、カスタマールーターで確認してください。' },
  { re: /^A LAG is a bandwidth aggregation mechanism, not a resiliency mechanism[\s\S]*$/,
    ko: () => 'LAG는 대역폭 집계 장치이지 복원력 장치가 아닙니다 — 모든 멤버 연결이 같은 로케이션의 같은 AWS 디바이스에 종단됩니다. min-links 파라미터로 LAG 유지에 필요한 최소 활성 멤버 수를 정의하세요. min-links가 없으면 심하게 저하된 LAG가 페일오버 대신 감소된 용량으로 계속 트래픽을 전달합니다. 혼잡 전에 깔끔한 페일오버를 강제하려면 n/2+1(과반), 외부 이중화가 전체 트래픽을 흡수할 수 있으면 1로 설정하세요.',
    zh: () => 'LAG 是带宽聚合机制而非弹性机制 — 所有成员连接都终结在同一位置的同一 AWS 设备上。请配置 min-links 参数定义 LAG 保持可用所需的最少活跃成员数。没有 min-links 时，严重降级的 LAG 会以降低的容量继续转发流量而不触发切换。设为 n/2+1（多数）可在拥塞前强制干净切换；外部冗余可承接全部流量时可设为 1。',
    ja: () => 'LAG は帯域集約の仕組みでありレジリエンス機構ではありません — 全メンバー接続が同一ロケーションの同一 AWS デバイスに終端します。min-links パラメータで LAG の稼働に必要な最小アクティブメンバー数を定義してください。min-links がないと、大きく劣化した LAG がフェイルオーバーせず縮退容量で転送を続けます。輻輳前にクリーンな切替を強制するには n/2+1（過半数）、外部冗長が全トラフィックを吸収できるなら 1 に設定します。' },
  { re: /^The following VIFs are at or above the 100-prefix limit for on-premises → AWS advertisement: (.+?)\. Exceeding the limit[\s\S]*$/,
    ko: (m) => `다음 VIF가 온프레미스→AWS 광고 100 프리픽스 한도에 도달했거나 초과했습니다: ${m[1]}. 한도 초과는 BGP 세션 종료와 네트워크 단절을 유발합니다. 즉시 온프레미스 라우트를 요약하거나 필터링하세요. 참고: https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html`,
    zh: (m) => `以下 VIF 的本地→AWS 通告已达到或超过 100 前缀上限：${m[1]}。超限将导致 BGP 会话中断与网络断连。请立即汇总或过滤本地路由。参见 https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html`,
    ja: (m) => `次の VIF がオンプレミス→AWS 広告の 100 プレフィックス上限に到達または超過しています: ${m[1]}。超過は BGP セッション切断とネットワーク断を招きます。直ちにオンプレミスルートを集約またはフィルタしてください。参考: https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html` },
  { re: /^The following VIFs are within 20 prefixes of the 100-prefix hard limit: (.+?)\. Plan summarization[\s\S]*$/,
    ko: (m) => `다음 VIF가 100 프리픽스 하드 한도까지 20개 이내로 근접했습니다: ${m[1]}. 온프레미스 증설이 BGP 세션 종료를 유발하지 않도록 지금 요약을 계획하세요. 참고: https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html`,
    zh: (m) => `以下 VIF 距 100 前缀硬上限已不足 20 条：${m[1]}。请现在规划路由汇总，避免本地增长触发 BGP 会话中断。参见 https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html`,
    ja: (m) => `次の VIF が 100 プレフィックスのハード上限まで 20 以内に迫っています: ${m[1]}。オンプレミス側の増加が BGP セッション切断を招かないよう、今のうちに集約を計画してください。参考: https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html` },
  { re: /^All (\d+) private\/transit VIFs? (?:are|is) well under the 100-prefix hard limit — peak observed is (\d+) prefix(?:es)? accepted from on-premises\.$/,
    ko: (m) => `private/transit VIF ${m[1]}개 모두 100 프리픽스 하드 한도에 충분히 여유가 있습니다 — 온프레미스에서 수신된 최대치는 ${m[2]}개입니다.`,
    zh: (m) => `全部 ${m[1]} 个 private/transit VIF 均远低于 100 前缀硬上限 — 从本地接收的峰值为 ${m[2]} 条。`,
    ja: (m) => `private/transit VIF ${m[1]} 本すべてが 100 プレフィックス上限に対し十分な余裕があります — オンプレミスから受信した最大値は ${m[2]} 件です。` },
  { re: /^Private and transit Virtual Interfaces accept at most 100 routes per BGP session[\s\S]*?\((.+?)\)[\s\S]*$/,
    ko: (m) => `private/transit VIF는 온프레미스→AWS 방향으로 BGP 세션당 최대 100개 라우트만 수용합니다. 다음 VIF는 CloudWatch 프리픽스 메트릭이 없어(${m[1]}) 고객 라우터에서 직접 개수를 확인하고 필요 시 요약하세요. 참고: https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html`,
    zh: (m) => `private/transit VIF 在本地→AWS 方向每个 BGP 会话最多接受 100 条路由。以下 VIF 无 CloudWatch 前缀指标（${m[1]}）— 请在客户路由器上直接确认数量并按需汇总。参见 https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html`,
    ja: (m) => `private/transit VIF はオンプレミス→AWS 方向で BGP セッションあたり最大 100 ルートまで受け入れます。次の VIF は CloudWatch プレフィックスメトリクスが取得できません（${m[1]}）— カスタマールーターで直接件数を確認し、必要なら集約してください。参考: https://docs.aws.amazon.com/directconnect/latest/UserGuide/limits.html` },
  { re: /^Each Site-to-Site VPN connection provides two tunnels for redundancy\. The following connection\(s\) do not have both tunnels UP: (.+?)\. Investigate[\s\S]*$/,
    ko: (m) => `Site-to-Site VPN 연결은 이중화를 위해 터널 2개를 제공합니다. 다음 연결은 두 터널이 모두 UP이 아닙니다: ${m[1]}. Customer Gateway 설정과 터널 상태를 점검해 이중화를 복구하세요.`,
    zh: (m) => `每条 Site-to-Site VPN 连接提供两条隧道以实现冗余。以下连接的两条隧道未全部 UP：${m[1]}。请检查 Customer Gateway 配置与隧道健康状况以恢复冗余。`,
    ja: (m) => `Site-to-Site VPN 接続は冗長性のためトンネルを 2 本提供します。次の接続は 2 本とも UP ではありません: ${m[1]}。Customer Gateway の設定とトンネル状態を確認し、冗長性を回復してください。` },
  { re: /^All Site-to-Site VPN connections terminate on the same customer gateway[\s\S]*$/,
    ko: () => '모든 Site-to-Site VPN 연결이 같은 Customer Gateway에 종단됩니다. 단일 CGW(또는 DX 파트너 디바이스)는 단일 장애점입니다 — 디바이스 장애가 하이브리드 네트워크 전체를 끊지 않도록 CGW를 2대 이상 배치하세요.',
    zh: () => '所有 Site-to-Site VPN 连接终结在同一 Customer Gateway 上。单一 CGW（或 DX 合作伙伴设备）是单点故障 — 请部署至少两台 CGW，避免设备故障导致混合网络中断。',
    ja: () => 'すべての Site-to-Site VPN 接続が同一の Customer Gateway に終端しています。単一の CGW（または DX パートナーデバイス）は単一障害点です — デバイス障害でハイブリッドネットワーク全体が落ちないよう、CGW を 2 台以上配置してください。' },
  { re: /^All Direct Connect connections are sourced from the same partner\/last-mile provider \((.+?)\)\.[\s\S]*$/,
    ko: (m) => `모든 Direct Connect 연결이 같은 파트너/라스트마일 사업자(${m[1]})에서 조달됐습니다. 예산이 허락하면 복수 파트너에서 DX를 조달해 파트너 측 단일 장애점(파트너망 장애, 파트너 유지보수)을 최소화하세요.`,
    zh: (m) => `所有 Direct Connect 连接均来自同一合作伙伴/最后一公里供应商（${m[1]}）。预算允许时，从多家合作伙伴采购 DX 可将合作伙伴侧的单点故障（网络故障、维护事件）风险降到最低。`,
    ja: (m) => `すべての Direct Connect 接続が同一のパートナー/ラストマイル事業者（${m[1]}）から調達されています。予算が許せば複数パートナーから DX を調達し、パートナー側の単一障害点（網障害、メンテナンス）を最小化してください。` },
  { re: /^The following VPN tunnel\(s\) are configured with DpdTimeoutAction=none[\s\S]*?probes: (.+?)\. Switch[\s\S]*$/,
    ko: (m) => `다음 VPN 터널이 DpdTimeoutAction=none으로 설정돼 있어, Customer Gateway가 DPD 프로브에 응답하지 않아도 AWS가 아무 조치를 하지 않습니다: ${m[1]}. ModifyVpnTunnelOptions로 옵션을 "clear" 또는 "restart"로 바꿔 피어 장애 후 페일오버가 지연되지 않게 하세요. Customer Gateway 측 DPD 설정도 확인이 필요합니다(AWS API로는 보이지 않음).`,
    zh: (m) => `以下 VPN 隧道配置为 DpdTimeoutAction=none，Customer Gateway 停止响应 DPD 探测时 AWS 不会采取任何操作：${m[1]}。请通过 ModifyVpnTunnelOptions 将该选项改为 "clear" 或 "restart"，避免对端故障后切换延迟。另请确认 Customer Gateway 侧的 DPD 配置（AWS API 不可见）。`,
    ja: (m) => `次の VPN トンネルが DpdTimeoutAction=none に設定されており、Customer Gateway が DPD プローブに応答しなくなっても AWS は何も行いません: ${m[1]}。ModifyVpnTunnelOptions でオプションを "clear" または "restart" に変更し、ピア障害後のフェイルオーバーが遅延しないようにしてください。Customer Gateway 側の DPD 設定も確認が必要です（AWS API では見えません）。` },
  { re: /^AWS-side DPD is configured on every tunnel[\s\S]*$/,
    ko: () => 'AWS 측 DPD는 모든 터널에 구성돼 있습니다(DpdTimeoutAction=clear/restart). 양쪽에서 장애 터널을 빠르게 감지하도록 Customer Gateway 측에도 DPD가 구성돼 있는지 확인하세요 — CGW 측 DPD 설정은 AWS API로 노출되지 않습니다.',
    zh: () => 'AWS 侧 DPD 已在所有隧道上配置（DpdTimeoutAction=clear/restart）。请确认 Customer Gateway 侧也配置了 DPD，以便双向快速检测故障隧道 — CGW 侧 DPD 配置不会通过 AWS API 暴露。',
    ja: () => 'AWS 側 DPD はすべてのトンネルで構成済みです（DpdTimeoutAction=clear/restart）。障害トンネルを両側から迅速に検出できるよう、Customer Gateway 側にも DPD が構成されているか確認してください — CGW 側の DPD 設定は AWS API では公開されません。' },
  { re: /^Metro diversity \(DX locations in the same metro\)[\s\S]*$/,
    ko: () => '메트로 다양성(같은 메트로 내 DX 로케이션)은 낮은 지연의 빠른 페일오버와 단일 시설 장애(전원·냉각·건물 단위 광케이블 절단) 보호를 더 낮은 크로스커넥트 비용으로 제공합니다. 지리적 다양성(서로 다른 지역의 DX 로케이션)은 대규모 지역 이벤트(자연재해, 메트로 전체 광케이블 절단, 전력망 장애)까지 보호하지만 백업 경로 지연과 회선 비용이 높아집니다. 고가용성엔 메트로 다양성으로 충분한 경우가 많고, 대재해 수준의 지역 이벤트 대비가 필요할 때 지리적 다양성을 선택하세요.',
    zh: () => 'Metro 多样性（同一都会区内的 DX 位置）以更低的交叉连接成本提供快速低延迟切换，并防护单设施故障（供电、制冷、单楼光纤中断）。地理多样性（不同区域的 DX 位置）可防护大规模区域事件（自然灾害、全城光纤中断、电网故障），代价是备份路径延迟更高、线路成本更高。高可用通常 Metro 多样性已足够；业务连续性需抵御灾难级区域事件时选择地理多样性。',
    ja: () => 'メトロ多様性（同一都市圏内の DX ロケーション）は、低いクロスコネクト費用で低遅延の高速フェイルオーバーと単一施設障害（電源・冷却・建物単位のファイバー切断）への保護を提供します。地理的多様性（別リージョンの DX ロケーション）は大規模な地域イベント（自然災害、都市圏全体のファイバー切断、送電網障害）まで保護しますが、バックアップ経路の遅延と回線費用が増えます。高可用性にはメトロ多様性で十分なことが多く、壊滅的な地域イベントへの耐性が必要なら地理的多様性を選んでください。' },
  { re: /^If the customer gateway or partner device does not support BFD[\s\S]*$/,
    ko: () => 'Customer Gateway나 파트너 디바이스가 BFD를 지원하지 않으면, 세션 안정성을 유지하는 선에서 BGP hold 타이머를 약 20–30초로 낮춰 장애 감지 시간을 줄이세요. AWS 기본 hold 타이머는 90초라 페일오버가 크게 지연됩니다.',
    zh: () => '若 Customer Gateway 或合作伙伴设备不支持 BFD，请在保持会话稳定的前提下将 BGP 保持计时器调低到约 20–30 秒，以缩短故障检测时间。AWS 默认保持计时器为 90 秒，会显著延迟切换。',
    ja: () => 'Customer Gateway やパートナーデバイスが BFD に対応していない場合、セッションの安定を保てる範囲で BGP ホールドタイマーを約 20–30 秒に下げ、障害検出時間を短縮してください。AWS のデフォルトは 90 秒で、フェイルオーバーが大きく遅延します。' },
  { re: /^Exercise your redundant paths on a schedule[\s\S]*$/,
    ko: () => '중복 경로를 정기적으로 훈련하세요. AWS는 VIF의 BGP 피어를 AWS 측에서 최대 72시간 임시로 내릴 수 있게 해줘, 라우터 유지보수를 모사하고 실제 상황 전에 페일오버를 검증할 수 있습니다. 참고: 파트너 제공/hosted VIF는 파트너 모니터링 대상일 수 있으니 테스트 전에 DX 파트너와 조율하세요.',
    zh: () => '请按计划演练冗余路径。AWS 允许从 AWS 侧临时关闭 VIF 的 BGP 对等体最长 72 小时，可模拟路由器维护并在真实故障前验证切换。注意：合作伙伴提供/托管的 VIF 可能处于合作伙伴监控之下 — 演练前请与 DX 合作伙伴协调。',
    ja: () => '冗長経路を定期的に訓練してください。AWS では VIF の BGP ピアを AWS 側から最長 72 時間一時停止でき、ルーターメンテナンスを模擬して本番前にフェイルオーバーを検証できます。注: パートナー提供/hosted VIF はパートナー監視下にある場合があるため、テスト前に DX パートナーと調整してください。' },
  { re: /^Create and maintain operational runbooks for Direct Connect and VPN failover[\s\S]*$/,
    ko: () => 'Direct Connect·VPN 페일오버 절차의 운영 런북을 작성·유지하세요(에스컬레이션 경로, 온콜 로테이션, 파트너 협조 단계 포함). 인시던트 상황에서 잘 훈련된 런북이 페일오버를 수 시간의 혼란이 아닌 반복 가능한 절차로 만듭니다.',
    zh: () => '请编写并维护 Direct Connect 与 VPN 故障切换的运维手册（含升级路径、值班轮换、合作伙伴协调步骤）。事故发生时，经过演练的手册能把切换从数小时的慌乱变成可重复的流程。',
    ja: () => 'Direct Connect・VPN フェイルオーバー手順の運用 Runbook を作成・維持してください（エスカレーション経路、オンコール、パートナー連携手順を含む）。インシデント時、訓練済みの Runbook がフェイルオーバーを数時間の混乱ではなく再現可能な手順に変えます。' },
];

/** 엔진 생성 문자열(영어)을 표시 언어로 변환 — 미매칭은 원문 통과. */
export function localizeDxText(s: string, lang: Lang): string {
  if (lang === 'en') return s;
  for (const e of T) {
    const m = s.match(e.re);
    if (m) return e[lang](m);
  }
  return s;
}

/** 테스트용: 패턴 테이블 노출 (커버리지 검사). */
export const _DX_L10N_PATTERNS = T.map((e) => e.re);
